#!/bin/bash
# Build, sign and package the Tibetan Translation Trainer for TestFlight.
# Usage: bash ios/testflight/build.sh <TEAM_ID>
set -euo pipefail
TEAM="${1:?pass the 10-character Apple Developer Team ID}"
export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/dist/ios"; rm -rf "$OUT"; mkdir -p "$OUT/Payload"
APP="$OUT/Payload/TibetanTrainer.app"; mkdir -p "$APP"

echo "== 1. the drill pack (generated by allcore, not by the phone) =="
cmake --build "$ROOT/build" -j8 --target build_drill_pack >/dev/null
"$ROOT/build/core/build_drill_pack" "$ROOT/build/hgm_spine_v27_2.db" "$APP/drills.json" 4000

echo "== 2. compile for the device =="
SDK=$(xcrun --sdk iphoneos --show-sdk-path)
xcrun --sdk iphoneos swiftc -parse-as-library \
  -target arm64-apple-ios17.0 -sdk "$SDK" -O -whole-module-optimization \
  "$ROOT/ios/DiamondDrills/DiamondDrills.swift" -o "$APP/TibetanTrainer"

echo "== 3. icon =="
xcrun actool "$ROOT/ios/DiamondDrills/Assets.xcassets" --compile "$APP" \
  --platform iphoneos --minimum-deployment-target 17.0 --app-icon AppIcon \
  --output-partial-info-plist "$OUT/icon.plist" >/dev/null

echo "== 4. Info.plist =="
python3 - "$APP" "$OUT/icon.plist" <<'PY'
import plistlib, sys, os
app, part = sys.argv[1], sys.argv[2]
d = {
  "CFBundleName": "Tibetan Trainer",
  "CFBundleDisplayName": "Tibetan Trainer",
  "CFBundleIdentifier": "org.asianlegacylibrary.DiamondDrills",
  "CFBundleExecutable": "TibetanTrainer",
  "CFBundleVersion": "1", "CFBundleShortVersionString": "0.1",
  "CFBundlePackageType": "APPL", "LSRequiresIPhoneOS": True,
  "MinimumOSVersion": "17.0", "UILaunchScreen": {},
  "UISupportedInterfaceOrientations": ["UIInterfaceOrientationPortrait"],
  "ITSAppUsesNonExemptEncryption": False,
}
if os.path.exists(part): d.update(plistlib.load(open(part, "rb")))
plistlib.dump(d, open(os.path.join(app, "Info.plist"), "wb"), fmt=plistlib.FMT_BINARY)
PY

echo "== 5. sign =="
IDENT=$(security find-identity -v -p codesigning | grep -m1 "Apple Develop" | sed -E 's/.*"([^"]+)".*/\1/')
[ -n "$IDENT" ] || { echo "no Apple Development identity in the keychain — create it in Xcode ▸ Settings ▸ Accounts"; exit 1; }
echo "   signing as: $IDENT   team: $TEAM"
codesign --force --sign "$IDENT" --timestamp=none "$APP"

echo "== 6. package =="
(cd "$OUT" && zip -qr TibetanTrainer.ipa Payload)
echo "PACKAGED: $OUT/TibetanTrainer.ipa"
echo "Upload with Transporter.app, or:"
echo "  xcrun altool --upload-app -f \"$OUT/TibetanTrainer.ipa\" -t ios --apiKey <key> --apiIssuer <issuer>"
