// catalog_list.cpp — see allcore/catalog_list.h.
#include "allcore/catalog_list.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <vector>

#include "allcore/catalog_id.h"
#include "allcore/tibexport.h"

namespace allcore {
namespace {

std::string upperName(const std::filesystem::path& p) {
    std::string s = p.filename().string();
    for (char& c : s)
        c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    return s;
}

// first and last "@NNN[AB]" folio marks in the body
std::pair<std::string, std::string> folioRange(const std::string& body) {
    std::string first, last;
    for (size_t at = body.find('@'); at != std::string::npos;
         at = body.find('@', at + 1)) {
        size_t j = at + 1;
        while (j < body.size() && body[j] == ' ') ++j;
        size_t d = j;
        while (d < body.size() &&
               std::isdigit(static_cast<unsigned char>(body[d])))
            ++d;
        if (d == j || d >= body.size()) continue;
        const char side =
            static_cast<char>(std::toupper(static_cast<unsigned char>(body[d])));
        if (side != 'A' && side != 'B') continue;
        std::string f = body.substr(j, d - j);
        f.push_back(side);
        if (first.empty()) first = f;
        last = std::move(f);
    }
    return {first, last};
}

}  // namespace

AsciiCatalogResult generateAsciiCatalog(const std::string& root) {
    namespace fs = std::filesystem;
    AsciiCatalogResult r;
    std::error_code ec;

    std::vector<fs::path> files;
    if (fs::exists(root, ec)) {
        for (fs::recursive_directory_iterator it(
                 root, fs::directory_options::skip_permission_denied, ec),
             end;
             it != end; it.increment(ec)) {
            if (ec) break;
            if (!it->is_regular_file(ec)) continue;
            const std::string up = upperName(it->path());
            const size_t dot = up.rfind('.');
            const std::string ext =
                dot == std::string::npos ? "" : up.substr(dot);
            if (ext != ".TXT" && ext != ".ACT" && ext != ".INC" &&
                ext != ".ACE")
                continue;
            if (up.find(" META.") != std::string::npos) continue;
            files.push_back(it->path());
        }
    }
    std::sort(files.begin(), files.end());

    std::ostringstream out;
    out << "; ASCII catalog list - generated by the ALL Translation "
           "Tool\n"
        << "; A LIST of what the folders hold, in the lineage of the "
           "ACIP/St. Petersburg\n"
        << "; field-coded catalogs (S number, T title, A author...). "
           "This is NOT the\n"
        << "; official catalog: the catalog changes only through data "
           "releases.\n"
        << "; Root: " << root << "\n"
        << "; Encoding: structure and field codes are plain ASCII; "
           "field values are\n"
        << "; verbatim (UTF-8 where filenames carry diacritics) - a "
           "pointer to a file\n"
        << "; must name the file exactly.\n"
        << "; Fields: S catalog-number | F filename | D folder | "
           "T Tibetan title\n"
        << ";         (T* = read from the text's own title page) | "
           "E English title |\n"
        << ";         A author | V status | P size/lines/folios\n"
        << ";\n";

    for (const auto& p : files) {
        ++r.stats.files;
        const std::string name = p.filename().string();
        const auto inf = decodeAcipFilename(name);
        if (inf.recognized) ++r.stats.cataloged;
        else ++r.stats.uncataloged;

        // filename fields: NUMBER_TIB_ENG_AUTHOR — but the grammar
        // only MEANS anything when the name decodes as an ACIP name;
        // an arbitrary intake name like "mystery_scan.txt" must not
        // have its underscores mistaken for title fields
        std::string stem = name;
        const size_t dot = stem.rfind('.');
        if (dot != std::string::npos) stem.erase(dot);
        std::vector<std::string> fields;
        size_t start = 0;
        while (true) {
            const size_t u = stem.find('_', start);
            if (u == std::string::npos) {
                fields.push_back(stem.substr(start));
                break;
            }
            fields.push_back(stem.substr(start, u - start));
            start = u + 1;
        }

        std::ifstream f(p, std::ios::binary);
        std::ostringstream ss;
        ss << f.rdbuf();
        const std::string body = ss.str();
        int lines = 0;
        for (char c : body)
            if (c == '\n') ++lines;
        const auto [fol1, fol2] = folioRange(body);

        out << "S: "
            << (inf.recognized ? fields[0] : std::string("uncataloged"))
            << "\n";
        out << "F: " << name << "\n";
        const std::string rel =
            fs::relative(p.parent_path(), root, ec).string();
        if (!rel.empty() && rel != ".") out << "D: " << rel << "\n";
        if (inf.recognized && fields.size() >= 2 && !fields[1].empty()) {
            out << "T: " << fields[1] << "\n";
        } else {
            // no title in the name: read the text's own title page and
            // MARK the provenance (rule 3: never silently)
            const auto t = extractAcipTitle(body.substr(
                0, std::min<size_t>(body.size(), 4000)));
            if (t.found) {
                out << "T*: " << t.title << "\n";
                ++r.stats.titled_from_text;
            }
        }
        if (inf.recognized && fields.size() >= 3 && !fields[2].empty())
            out << "E: " << fields[2] << "\n";
        if (inf.recognized && fields.size() >= 4 && !fields[3].empty())
            out << "A: " << fields[3] << "\n";
        if (inf.recognized) {
            std::string v = inf.status;
            if (!inf.language.empty()) v += " - " + inf.language;
            if (inf.incomplete) v += " - incomplete";
            out << "V: " << v << "\n";
        }
        out << "P: " << (body.size() + 512) / 1024 << " KB - " << lines
            << " lines";
        if (!fol1.empty()) out << " - folios " << fol1 << "-" << fol2;
        out << "\n\n";
    }
    r.text = out.str();
    return r;
}

}  // namespace allcore
