#include "allcore/tibdisplay.h"

#include "allcore/engines.h"

namespace allcore {
namespace {
// Three ACIP forms acip_to_ewts does not read, so a reader saw ⟨g-yas⟩,
// ⟨g-yon⟩ and ⟨dvags⟩ where Tibetan belonged (Adam, 2026-09-09).
//
// The correct fix is in the engine — G-Y is EWTS g.y, V is wa-zur w, ':' is
// visarga H — and it was written, measured and then DELIBERATELY NOT SHIPPED
// there. The reason is recorded in docs/FINDING_ACIP_EWTS_GAPS.md: the
// canonical engine's output is compared against the wylie column banked in the
// spine, which was generated by the old engine, and correcting the engine
// drops that agreement from 99.5% to 93.4% on 6.6% of segments. The spine is
// the release package's data and regenerating it is the data project's call,
// not something to do at the end of an evening.
//
// So the correction lives here, in the DISPLAY path: what the reader sees is
// right, nothing banked is contradicted, and the engine fix stays queued as a
// coordinated change. Guarded by context, because the ACIP field is not always
// ACIP — ':' is usually English punctuation there ("the first path:
// renunciation"), and converting it blindly is what caused the 6.6%.
std::string fixForDisplay(const std::string& acip) {
    auto isUp = [](char c) { return c >= 'A' && c <= 'Z'; };
    auto isLo = [](char c) { return c >= 'a' && c <= 'z'; };
    std::string o;
    for (size_t i = 0; i < acip.size();) {
        if (acip.compare(i, 3, "G-Y") == 0 &&
            (i == 0 || !(isUp(acip[i - 1]) || isLo(acip[i - 1])))) {
            o += "G.Y"; i += 3; continue;
        }
        if (acip[i] == 'V' && i > 0 && isUp(acip[i - 1]) &&
            i + 1 < acip.size() && isUp(acip[i + 1])) {
            o += 'W'; ++i; continue;
        }
        // NOT the visarga. EWTS is case-sensitive — "H" is the visarga and "h"
        // is ha — and acip_to_ewts lowercases everything it is not told to
        // protect, so ':' handled here rendered A'A: as ཨའཧ, "a-ha", instead
        // of ཨའཿ. A wrong glyph is worse than an honest flag, so the visarga
        // stays flagged until the engine itself is fixed (2026-09-09).
        o += acip[i++];
    }
    return o;
}

bool isMarkupChar(char c) {
    return c == '{' || c == '}' || c == '(' || c == ')' || c == '[' ||
           c == ']' || c == '@' || c == '*' || c == '%' || c == '#';
}
}  // namespace

std::vector<DisplayPiece> acipDisplayPieces(const std::string& acip) {
    // A RUN at a time, not a token at a time. Converting each space-separated
    // token alone throws away the context the engine needs: a bare "," is a
    // shad and converts to nothing on its own, while "sangs rgyas, ,bcom ldan"
    // converts perfectly — and the shad alone accounted for 61% of all failures
    // in the first drill pack (1,945 of 3,178). Runs are split only at
    // editorial markup, which is the one thing that must never be converted.
    std::vector<DisplayPiece> out;
    std::string cur, mark;
    auto flushMark = [&] {
        if (mark.empty()) return;
        out.push_back({DisplayPiece::Markup, mark});
        mark.clear();
    };
    auto flush = [&] {
        if (cur.empty()) return;
        // trim, so a trailing space in a run does not become a failure
        size_t b = cur.find_first_not_of(' ');
        size_t e = cur.find_last_not_of(' ');
        if (b == std::string::npos) { cur.clear(); return; }
        const std::string run = cur.substr(b, e - b + 1);
        auto [u, ok] = wylieToUnicode(acipToEwts(fixForDisplay(run)));
        if (ok && !u.empty())
            out.push_back({DisplayPiece::Script, u});
        else if (!u.empty())
            // The engine converts what it can and marks the rest in ⟨ ⟩ itself.
            // Keep its partial rendering: a run of good Tibetan must not be
            // thrown away because one syllable in it would not convert.
            out.push_back({DisplayPiece::Script, u});
        else
            out.push_back({DisplayPiece::Failed, run});
        cur.clear();
    };
    for (char c : acip) {
        if (isMarkupChar(c)) { flush(); mark += c; }
        else { flushMark(); cur += c; }
    }
    flush();
    flushMark();
    return out;
}

std::string acipToTibetanPlain(const std::string& acip) {
    std::string out;
    for (const auto& p : acipDisplayPieces(acip))
        out += p.kind == DisplayPiece::Failed
                   ? "⟨" + p.text + "⟩"
                   : p.text;
    return out;
}

std::string acipStripMarkup(const std::string& acip) {
    std::string out;
    for (char c : acip)
        if (!isMarkupChar(c)) out += c;
    // collapse the whitespace the removal leaves behind
    std::string t;
    bool sp = false;
    for (char c : out) {
        if (c == ' ') { sp = true; continue; }
        if (sp && !t.empty()) t += ' ';
        sp = false;
        t += c;
    }
    return t;
}

}  // namespace allcore
