// engines_battery — the validation batteries for the C++ engine ports
// (founding rule 2: a port that fails its battery does not ship).
//
//  A. acipToEwts   vs all corpus segments: the stored wylie was generated by
//     the canonical Python acip_to_ewts from the stored acip, so the port
//     must reproduce it. 35,601 pairs.
//  B. wylieToUnicode vs the master's 26,318 source-attested (wylie, tibetan)
//     ground-truth pairs, variant-aware and shad-segment-aware — the same
//     battery the Python engine passes at 99.03%.
#include <sqlite3.h>

#include <cstdio>
#include <map>
#include <set>
#include <string>
#include <vector>

#include "allcore/engines.h"
#include "allcore/sanskrit.h"

static int failures = 0;
#define CHECK(cond, msg)                                        \
    do {                                                        \
        if (cond) std::printf("  [PASS] %s\n", msg);            \
        else { std::printf("  [FAIL] %s\n", msg); ++failures; } \
    } while (0)

static std::string colText(sqlite3_stmt* s, int c) {
    const unsigned char* t = sqlite3_column_text(s, c);
    return t ? reinterpret_cast<const char*>(t) : "";
}

// Tibetan canonical decompositions (composition-excluded, so Python's NFC
// normalization DECOMPOSES these — the battery must match that behavior).
static std::string decomposeTibetan(const std::string& in) {
    static const std::pair<const char*, const char*> D[] = {
        // {precomposed codepoint, canonical decomposition} as UTF-8 escapes
        {"\xE0\xBD\x83", "\xE0\xBD\x82\xE0\xBE\xB7"},  // 0F43 gha  -> 0F42 0FB7
        {"\xE0\xBD\x8D", "\xE0\xBD\x8C\xE0\xBE\xB7"},  // 0F4D Dha  -> 0F4C 0FB7
        {"\xE0\xBD\x92", "\xE0\xBD\x91\xE0\xBE\xB7"},  // 0F52 dha  -> 0F51 0FB7
        {"\xE0\xBD\x97", "\xE0\xBD\x96\xE0\xBE\xB7"},  // 0F57 bha  -> 0F56 0FB7
        {"\xE0\xBD\x9C", "\xE0\xBD\x9B\xE0\xBE\xB7"},  // 0F5C dzha -> 0F5B 0FB7
        {"\xE0\xBD\xA9", "\xE0\xBD\x80\xE0\xBE\xB5"},  // 0F69 kSha -> 0F40 0FB5
        {"\xE0\xBD\xB3", "\xE0\xBD\xB1\xE0\xBD\xB2"},  // 0F73 II   -> 0F71 0F72
        {"\xE0\xBD\xB5", "\xE0\xBD\xB1\xE0\xBD\xB4"},  // 0F75 UU   -> 0F71 0F74
        {"\xE0\xBD\xB6", "\xE0\xBE\xB2\xE0\xBE\x80"},  // 0F76 r-i  -> 0FB2 0F80
        {"\xE0\xBD\xB8", "\xE0\xBE\xB3\xE0\xBE\x80"},  // 0F78 l-i  -> 0FB3 0F80
        {"\xE0\xBE\x81", "\xE0\xBD\xB1\xE0\xBE\x80"},  // 0F81 -II  -> 0F71 0F80
        {"\xE0\xBE\x93", "\xE0\xBE\x92\xE0\xBE\xB7"},  // 0F93 sub gha
        {"\xE0\xBE\x9D", "\xE0\xBE\x9C\xE0\xBE\xB7"},  // 0F9D sub Dha
        {"\xE0\xBE\xA2", "\xE0\xBE\xA1\xE0\xBE\xB7"},  // 0FA2 sub dha
        {"\xE0\xBE\xA7", "\xE0\xBE\xA6\xE0\xBE\xB7"},  // 0FA7 sub bha
        {"\xE0\xBE\xAC", "\xE0\xBE\xAB\xE0\xBE\xB7"},  // 0FAC sub dzha
        {"\xE0\xBE\xB9", "\xE0\xBE\x90\xE0\xBE\xB5"},  // 0FB9 sub kSha
    };
    std::string s = in;
    for (const auto& [from, to] : D) {
        const std::string f = from, t = to;
        size_t pos = 0;
        while ((pos = s.find(f, pos)) != std::string::npos) {
            s.replace(pos, f.size(), t);
            pos += t.size();
        }
    }
    return s;
}

// normalize tibetan for comparison: strip spaces/NBSP, rstrip tsheg+shad
static std::string normTib(const std::string& raw) {
    const std::string in = decomposeTibetan(raw);
    std::string s;
    for (size_t i = 0; i < in.size();) {
        if (in[i] == ' ') { ++i; continue; }
        if (i + 1 < in.size() && (unsigned char)in[i] == 0xC2 &&
            (unsigned char)in[i + 1] == 0xA0) { i += 2; continue; }
        s += in[i++];
    }
    const std::string TSHEG = "་", SHAD = "།";
    bool trimmed = true;
    while (trimmed) {
        trimmed = false;
        for (const auto& suf : {TSHEG, SHAD}) {
            if (s.size() >= suf.size() &&
                s.compare(s.size() - suf.size(), suf.size(), suf) == 0) {
                s.resize(s.size() - suf.size());
                trimmed = true;
            }
        }
    }
    return s;
}

static std::vector<std::string> shadSegments(const std::string& tib) {
    std::vector<std::string> segs;
    std::string cur;
    for (size_t i = 0; i < tib.size();) {
        if (tib.compare(i, 3, "།") == 0 || tib.compare(i, 3, "༔") == 0) {
            if (!normTib(cur).empty()) segs.push_back(normTib(cur));
            cur.clear();
            i += 3;
        } else {
            cur += tib[i++];
        }
    }
    if (!normTib(cur).empty()) segs.push_back(normTib(cur));
    segs.push_back(normTib(tib));   // whole-field form counts too
    return segs;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        std::fprintf(stderr, "usage: engines_battery <spine.db>\n");
        return 2;
    }
    sqlite3* db = nullptr;
    if (sqlite3_open_v2(argv[1], &db, SQLITE_OPEN_READONLY, nullptr) != SQLITE_OK) {
        std::fprintf(stderr, "cannot open %s\n", argv[1]);
        return 2;
    }

    // ---- Battery A: acipToEwts over the whole corpus ----
    {
        sqlite3_stmt* s = nullptr;
        sqlite3_prepare_v2(db,
                           "SELECT acip, wylie FROM corpus_segments "
                           "WHERE acip IS NOT NULL AND wylie IS NOT NULL",
                           -1, &s, nullptr);
        long total = 0, match = 0;
        std::vector<std::pair<std::string, std::string>> misses;
        while (sqlite3_step(s) == SQLITE_ROW) {
            const std::string acip = colText(s, 0), want = colText(s, 1);
            ++total;
            const std::string got = allcore::acipToEwts(acip);
            if (got == want) ++match;
            else if (misses.size() < 5) misses.emplace_back(got, want);
        }
        sqlite3_finalize(s);
        const double rate = total ? 100.0 * match / total : 0;
        std::printf("  A: acipToEwts corpus battery: %ld/%ld (%.3f%%)\n", match,
                    total, rate);
        for (auto& [g, w] : misses)
            std::printf("     miss: got %.60s | want %.60s\n", g.c_str(), w.c_str());
        CHECK(total > 35000, "battery A covers the full corpus");
        CHECK(rate >= 99.5, "acipToEwts reproduces the canonical wylie (>=99.5%)");
    }

    // ---- Battery B: wylieToUnicode over the 26,318 ground-truth pairs ----
    {
        // variants
        std::map<long long, std::vector<std::string>> variants;
        {
            sqlite3_stmt* s = nullptr;
            sqlite3_prepare_v2(db, "SELECT entry_id, wylie FROM entry_variants", -1,
                               &s, nullptr);
            while (sqlite3_step(s) == SQLITE_ROW)
                variants[sqlite3_column_int64(s, 0)].push_back(colText(s, 1));
            sqlite3_finalize(s);
        }
        sqlite3_stmt* s = nullptr;
        sqlite3_prepare_v2(db,
                           "SELECT id, wylie, tibetan FROM entries "
                           "WHERE tibetan_source IS NULL AND tibetan IS NOT NULL "
                           "AND wylie IS NOT NULL AND wylie != ''",
                           -1, &s, nullptr);
        long total = 0, match = 0;
        std::vector<std::pair<std::string, std::string>> misses;
        while (sqlite3_step(s) == SQLITE_ROW) {
            const long long id = sqlite3_column_int64(s, 0);
            const std::string wylie = colText(s, 1), tib = colText(s, 2);
            ++total;
            auto targets = shadSegments(tib);
            std::vector<std::string> cands = {wylie};
            auto vi = variants.find(id);
            if (vi != variants.end())
                for (const auto& v : vi->second)
                    if (v != wylie) cands.push_back(v);
            bool hit = false;
            for (const auto& c : cands) {
                auto [u, ok] = allcore::wylieToUnicode(c);
                (void)ok;
                const std::string nu = normTib(u);
                for (const auto& t : targets)
                    if (nu == t) { hit = true; break; }
                if (hit) break;
            }
            if (hit) ++match;
            else if (misses.size() < 5) misses.emplace_back(wylie, tib);
        }
        sqlite3_finalize(s);
        const double rate = total ? 100.0 * match / total : 0;
        std::printf("  B: wylieToUnicode GT battery: %ld/%ld (%.3f%%)\n", match,
                    total, rate);
        for (auto& [w, t] : misses)
            std::printf("     miss: %.50s | %.60s\n", w.c_str(), t.c_str());
        CHECK(total >= 26000 && total <= 27000, "battery B covers the 26,318 GT pairs");
        CHECK(rate >= 99.0,
              "wylieToUnicode matches Python's validated rate (>=99.0%)");
    }

    // ---- Battery C: pronounce vs the canonical Python reference dump ----
    if (argc > 2) {
        FILE* f = std::fopen(argv[2], "r");
        if (!f) {
            std::printf("  C: reference file %s missing — SKIPPED\n", argv[2]);
            ++failures;
        } else {
            long total = 0, match = 0, segMiss = 0;
            char line[4096];
            std::vector<std::pair<std::string, std::string>> misses;
            while (std::fgets(line, sizeof line, f)) {
                std::string l(line);
                while (!l.empty() && (l.back() == '\n' || l.back() == '\r'))
                    l.pop_back();
                auto tab = l.find('\t');
                if (tab == std::string::npos) continue;
                const std::string wylie = l.substr(0, tab), want = l.substr(tab + 1);
                ++total;
                const std::string got = allcore::pronounce(wylie);
                if (got == want) ++match;
                else if (misses.size() < 6) misses.emplace_back(wylie, got + " != " + want);
                // the segmented view must be the SAME engine: joined
                // non-empty prons identical, spans a contiguous
                // partition from zero
                {
                    const auto segd = allcore::pronounceSegmented(wylie);
                    std::string joined;
                    int expectBeg = 0;
                    bool spansOk = true;
                    for (const auto& sw : segd) {
                        if (sw.syl_beg != expectBeg ||
                            sw.syl_end < sw.syl_beg)
                            spansOk = false;
                        expectBeg = sw.syl_end;
                        if (sw.pron.empty()) continue;
                        if (!joined.empty()) joined += ' ';
                        joined += sw.pron;
                    }
                    if (joined != got || !spansOk) {
                        ++segMiss;
                        if (segMiss <= 3)
                            std::printf("     seg-miss: %.60s\n",
                                        wylie.c_str());
                    }
                }
            }
            std::fclose(f);
            const double rate = total ? 100.0 * match / total : 0;
            std::printf("  C: pronounce full-dictionary diff: %ld/%ld (%.3f%%)\n",
                        match, total, rate);
            for (auto& [w, d] : misses)
                std::printf("     miss: %.40s | %.70s\n", w.c_str(), d.c_str());
            CHECK(total > 100000, "battery C covers the full dictionary");
            CHECK(match == total, "pronounce is IDENTICAL to the canonical engine");
            CHECK(segMiss == 0, "pronounceSegmented joins back to pronounce with contiguous spans");
        }
    }

    // ---- Battery D: card-attested pronunciations (Python: 895/1308 exact) ----
    {
        sqlite3_stmt* s = nullptr;
        sqlite3_prepare_v2(db,
                           "SELECT wylie, pronunciation FROM entries "
                           "WHERE pronunciation_source IS NOT NULL",
                           -1, &s, nullptr);
        long total = 0, match = 0;
        while (sqlite3_step(s) == SQLITE_ROW) {
            ++total;
            if (allcore::pronounce(colText(s, 0)) == colText(s, 1)) ++match;
        }
        sqlite3_finalize(s);
        std::printf("  D: card-attested battery: %ld/%ld exact (python: 895/1308; "
                    "differences are banked card-governed overrides)\n",
                    match, total);
        CHECK(total >= 1300 && total <= 1320, "battery D covers the card-attested set");
        CHECK(match == 895, "card-exact count matches the Python engine exactly");
    }

    // ---- Battery E: sanskrit — official standard-doc examples ----
    {
        // strip zero-width space, as validate_engines.py does for the tibetan check
        auto noZwsp = [](std::string s) {
            const std::string z = "\xE2\x80\x8B";
            size_t p = 0;
            while ((p = s.find(z, p)) != std::string::npos) s.erase(p, z.size());
            return s;
        };
        CHECK(allcore::iastToInputcode("pramāṇa") == "prama#n%a",
              "E: input-code pramāṇa == prama#n%a");
        CHECK(allcore::iastToNextletter("pramāṇa") == "prama-n.a",
              "E: next-letter pramāṇa == prama-n.a");
        CHECK(allcore::iastToAcip("pramāṇa") ==
                  std::make_pair(std::string("PRA M'A nA"), true),
              "E: tibetanized pramāṇa == PRA M'A nA");
        CHECK(allcore::iastToAcip("oṃ maṇi padme hūṃ") ==
                  std::make_pair(std::string("AOm MA nI PAD ME H'Um"), true),
              "E: tibetanized mani mantra");
        CHECK(noZwsp(allcore::iastToTibetan("oṃ maṇi padme hūṃ").first) ==
                  "ཨོཾ་མ་ཎི་པད་མེ་ཧཱུཾ",
              "E: tibetan mani mantra");
        CHECK(allcore::iastToDevanagari("oṃ maṇi padme hūṃ") ==
                  std::make_pair(std::string("ओं मणि पद्मे हूं"), true),
              "E: devanagari mani mantra");
        CHECK(allcore::inputcodeToIast("prama#n%a") == "pramāṇa",
              "E: roundtrip inputcode -> iast");
    }

    // ---- Battery F: sanskrit full diff vs the Python oracle (LC terms) ----
    if (argc > 3) {
        FILE* f = std::fopen(argv[3], "r");
        if (!f) {
            std::printf("  F: reference file %s missing — SKIPPED\n", argv[3]);
            ++failures;
        } else {
            const std::string NONE = "\xE2\x88\x85";   // ∅
            long total = 0, match = 0;
            std::vector<std::pair<std::string, std::string>> misses;
            char line[8192];
            while (std::fgets(line, sizeof line, f)) {
                std::string l(line);
                while (!l.empty() && (l.back() == '\n' || l.back() == '\r'))
                    l.pop_back();
                std::vector<std::string> col;
                size_t start = 0;
                for (size_t p = 0; p <= l.size(); ++p)
                    if (p == l.size() || l[p] == '\t') {
                        col.push_back(l.substr(start, p - start));
                        start = p + 1;
                    }
                if (col.size() != 9) continue;
                const std::string& t = col[0];
                ++total;
                auto opt = [&NONE](const std::pair<std::string, bool>& r) {
                    return r.second ? r.first : NONE;
                };
                auto acip = allcore::iastToAcip(t);
                const std::string got[8] = {
                    opt(acip),
                    opt(allcore::iastToDevanagari(t)),
                    allcore::iastToPronunciation(t),
                    allcore::iastToNextletter(t),
                    allcore::iastToInputcode(t),
                    acip.second ? allcore::acipToEwts(acip.first) : NONE,
                    opt(allcore::iastToTibetan(t)),
                    acip.second ? allcore::acipSanskritToIast(acip.first) : NONE,
                };
                bool ok = true;
                for (int k = 0; k < 8; ++k) ok &= (got[k] == col[k + 1]);
                if (ok) ++match;
                else if (misses.size() < 6) {
                    std::string d;
                    for (int k = 0; k < 8; ++k)
                        if (got[k] != col[k + 1])
                            d += " [" + std::to_string(k) + "] " + got[k] +
                                 " != " + col[k + 1];
                    misses.emplace_back(t, d);
                }
            }
            std::fclose(f);
            const double rate = total ? 100.0 * match / total : 0;
            std::printf("  F: sanskrit full LC diff vs Python oracle: %ld/%ld "
                        "(%.3f%%)\n", match, total, rate);
            for (auto& [t, d] : misses)
                std::printf("     miss %.30s:%.120s\n", t.c_str(), d.c_str());
            CHECK(total > 79000, "battery F covers the full LC term set");
            CHECK(match == total,
                  "sanskrit port is IDENTICAL to the canonical engine");
        }
    }

    // ---- Battery G: authentic pronunciation layer ----
    {
        // IPA spot checks against the sourced Classical-Sanskrit mapping
        CHECK(allcore::iastToIpa("saṃgha") ==
                  std::make_pair(std::string("sɐŋɡʱɐ"), true),
              "G: anusvara assimilates to the row nasal (saṃgha)");
        CHECK(allcore::iastToIpa("oṃ maṇi padme hūṃ") ==
                  std::make_pair(std::string("oːm mɐɳɪ pɐdmeː ɦuːm"), true),
              "G: mani mantra IPA");
        CHECK(allcore::iastToIpa("namaḥ") ==
                  std::make_pair(std::string("nɐmɐh"), true),
              "G: visarga renders as h");
        CHECK(allcore::devanagariToIast("ओं मणि पद्मे हूं") ==
                  std::make_pair(std::string("oṃ maṇi padme hūṃ"), true),
              "G: devanagari -> iast (mani mantra)");
        auto guide = allcore::sanskritLetterGuide("pramāṇa");
        bool hasRetroflexN = false, hasLongA = false;
        for (auto& [l, h] : guide) {
            hasRetroflexN |= (l == "ṇ");
            hasLongA |= (l == "ā");
        }
        CHECK(hasRetroflexN && hasLongA,
              "G: letter guide covers the diacritics present");
    }
    // Battery G2: devanagari round-trip over the full LC term set
    if (argc > 3) {
        FILE* f = std::fopen(argv[3], "r");
        if (f) {
            const std::string NONE = "\xE2\x88\x85";
            long total = 0, match = 0;
            std::vector<std::string> misses;
            char line[8192];
            while (std::fgets(line, sizeof line, f)) {
                std::string l(line);
                while (!l.empty() && (l.back() == '\n' || l.back() == '\r'))
                    l.pop_back();
                std::vector<std::string> col;
                size_t start = 0;
                for (size_t p = 0; p <= l.size(); ++p)
                    if (p == l.size() || l[p] == '\t') {
                        col.push_back(l.substr(start, p - start));
                        start = p + 1;
                    }
                if (col.size() != 9 || col[2] == NONE) continue;
                ++total;
                // whitespace runs are presentational (break characters like
                // "-" and "…" all render as spaces) — compare letters
                auto normSpace = [](const std::string& s) {
                    std::string o;
                    for (char c : s) {
                        if (c == ' ') {
                            if (!o.empty() && o.back() != ' ') o += c;
                        } else o += c;
                    }
                    while (!o.empty() && o.back() == ' ') o.pop_back();
                    return o;
                };
                auto [iast, ok1] = allcore::devanagariToIast(col[2]);
                auto [deva, ok2] = allcore::iastToDevanagari(iast);
                if (ok1 && ok2 && normSpace(deva) == normSpace(col[2])) ++match;
                else if (misses.size() < 5)
                    misses.push_back(col[0] + " | " + iast);
            }
            std::fclose(f);
            std::printf("  G2: devanagari->iast->devanagari round-trip: "
                        "%ld/%ld (%.3f%%)\n", match, total,
                        total ? 100.0 * match / total : 0);
            for (auto& m : misses) std::printf("     miss: %.90s\n", m.c_str());
            CHECK(total > 70000, "battery G2 covers the LC devanagari set");
            CHECK(match == total, "devanagari round-trip is exact");
        }
    }

    // ---- Battery H: the ACIP pronunciation standard's own chart examples ----
    // (ACIP Release IV manual pp. 174-178, banked in docs/standards/). The
    // canonical engine reproduces 51/52 pure-Tibetan examples (sole diff:
    // YIN PA'O diphthong); the Sanskrit-in-Tibetan-letters rows are
    // informative only — the engine is a Tibetan-phonetics engine.
    {
        struct Ex { const char* acip; const char* want; bool skt; };
        static const Ex kChart[] = {
            {"KA BA", "kawa", false}, {"TZONG KHA PA", "tsongkapa", false},
            {"DGA' BA", "gawa", false}, {"RE 'GA'", "renga", false},
            {"DGE LUGS PA", "gelukpa", false}, {"MA GHA DA", "maghada", true},
            {"NGA", "nga", false}, {"BLANG", "lang", false},
            {"DKA' NGAL", "ka-ngel", false}, {"CUNG ZAD", "chungse", false},
            {"CHOS", "chu", false}, {"JA RIN", "jarin", false},
            {"MTHA' MJUG", "tanjuk", false}, {"DMYAL BA", "nyelwa", false},
            {"CHA MNYAM", "cha-nyam", false}, {"t'IK CHEN", "tikchen", true},
            {"KO thA", "kota", true}, {"dA MA RU", "damaru", true},
            {"AUTTA RA shA dhA", "uttarashadha", true},
            {"PAn CHEN", "panchen", true}, {"GTAN", "ten", false},
            {"THAR PA", "tarpa", false}, {"GDAN", "den", false},
            {"DGA' LDAN", "ganden", false}, {"SINDHU RA", "sindhura", true},
            {"GNAS", "ne", false}, {"LAN", "len", false},
            {"DPA' BO", "pawo", false}, {"PHAN THOGS", "pentok", false},
            {"BAR DO", "bardo", false}, {"CHU 'BEBS", "chumbep", false},
            {"RAB TU TSA BA", "raptu tsawa", false},
            {"SAM BHO tA", "sambhota", true}, {"DMAN PA", "menpa", false},
            {"RIM PA", "rimpa", false}, {"GTZUG PHUD", "tsukpu", false},
            {"TSAR CHEN", "tsarchen", false}, {"RDZAS", "dze", false},
            {"GZA' 'DZIN", "sandzin", false}, {"WA", "wa", false},
            {"ZHEN PA", "shenpa", false}, {"ZAM PA", "sampa", false},
            {"'O MA", "oma", false}, {"YIN PA'O", "yinpao", false},
            {"BLA MA'I THUGS", "lamay tuk", false},
            {"G-YAR BA", "yarwa", false}, {"TSAR BA", "tsarwa", false},
            {"LE LO", "lelo", false}, {"GSAL BA", "selwa", false},
            {"BSHAD PA", "shepa", false}, {"SRID PA", "sipa", false},
            {"LHA", "hla", false}, {"RANG DBANG", "rangwang", false},
            {"LAN PA", "lenpa", false}, {"YID", "yi", false},
            {"LUS", "lu", false}, {"SLEB PA", "leppa", false},
            {"DGONGS PA", "gongpa", false}, {"BSOD NAMS", "sunam", false},
        };
        auto norm = [](std::string s) {
            std::string o;
            for (char c : s) {
                if (c >= 'A' && c <= 'Z') c = (char)(c - 'A' + 'a');
                if (c != ' ' && c != '-') o += c;
            }
            return o;
        };
        int tibTotal = 0, tibOk = 0, sktTotal = 0, sktOk = 0;
        for (const auto& ex : kChart) {
            const std::string got =
                norm(allcore::pronounce(allcore::acipToEwts(ex.acip)));
            const bool ok = got == norm(ex.want);
            if (ex.skt) { ++sktTotal; sktOk += ok; }
            else { ++tibTotal; tibOk += ok; }
        }
        std::printf("  H: ACIP pron-standard chart: pure-Tibetan %d/%d, "
                    "Sanskrit-in-Tibetan %d/%d (informative)\n",
                    tibOk, tibTotal, sktOk, sktTotal);
        CHECK(tibTotal == 51 && sktTotal == 8, "battery H covers the chart");
        CHECK(tibOk >= 50,
              "engine reproduces the standard's pure-Tibetan examples");
    }

    // ---- I: the reverse converter, round-tripped ----
    // ewtsToAcip is a NEW engine (no canonical original); its proof is
    // the round trip through the corpus-proven forward direction:
    // acipToEwts(ewtsToAcip(w)) must reproduce w for every dictionary
    // wylie. Mismatches print — never hidden.
    {
        sqlite3_stmt* q = nullptr;
        sqlite3_prepare_v2(db,
                           "SELECT wylie FROM entries WHERE wylie != ''",
                           -1, &q, nullptr);
        long total = 0, ok = 0, shown = 0;
        while (sqlite3_step(q) == SQLITE_ROW) {
            const char* w = (const char*)sqlite3_column_text(q, 0);
            if (!w) continue;
            ++total;
            const std::string back =
                allcore::acipToEwts(allcore::ewtsToAcip(w));
            if (back == w) {
                ++ok;
            } else if (shown < 8) {
                std::printf("    roundtrip diff: '%s' -> '%s'\n", w,
                            back.c_str());
                ++shown;
            }
        }
        sqlite3_finalize(q);
        std::printf("  I: wylie->ACIP->wylie round trip: %ld/%ld\n", ok,
                    total);
        CHECK(total > 100000 && ok * 1000 >= total * 995,
              "reverse converter round-trips 99.5%+ of the dictionary");
    }

    // ---- J: transliteration detection (ACIP vs wylie) ----
    {
        CHECK(!allcore::looksLikeWylie(
                  "SKABS 'DIR DNGOS SU BSTAN PA'I MTSHAN NYID,"),
              "J: plain ACIP is not wylie");
        CHECK(!allcore::looksLikeWylie(
                  "GYA GAR SKAD DU, ka nA ma pra dznyA pA ra mi tA, "
                  "BOD SKAD DU SHES RAB KYI PHA ROL TU PHYIN PA,"),
              "J: ACIP with a lowercase Sanskrit passage is still ACIP");
        CHECK(allcore::looksLikeWylie(
                  "blo sbyong snyan brgyud chen mo'i 'khrid yig "
                  "gzhan phan nyi ma zhes bya ba bzhugs so"),
              "J: lowercase wylie is wylie");
        CHECK(allcore::looksLikeWylie(
                  "bdag dang mkha' mnyam Sems can, SGRUB"),
              "J: a stray uppercase word does not flip a wylie doc");
        CHECK(allcore::tokenToEwts("SKABS") == "skabs",
              "J: tokenToEwts converts an ACIP token");
        CHECK(allcore::tokenToEwts("skabs") == "skabs",
              "J: tokenToEwts passes a wylie token through");
        CHECK(allcore::tokenToEwts("BRTZON") == "brtson",
              "J: tokenToEwts handles ACIP TZ");
    }

    sqlite3_close(db);
    std::printf("%s (%d failures)\n",
                failures ? "ENGINES BATTERY FAILED" : "ENGINES BATTERY OK", failures);
    return failures ? 1 : 0;
}
