// regenreg_smoke — approved-register regeneration: idempotent fold,
// decline fall-out, abbreviation layer round-trip through AbbrTable.
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>

#include "allcore/abbr.h"
#include "allcore/proposals.h"
#include "allcore/regenreg.h"

static int failures = 0;
#define CHECK(cond, msg)                                        \
    do {                                                        \
        if (cond) std::printf("  [PASS] %s\n", msg);            \
        else { std::printf("  [FAIL] %s\n", msg); ++failures; } \
    } while (0)

namespace fs = std::filesystem;

static void write(const fs::path& p, const char* text) {
    std::ofstream f(p);
    f << text;
}

static std::string slurp(const fs::path& p) {
    std::ifstream f(p);
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

int main() {
    setvbuf(stdout, nullptr, _IONBF, 0);
    const fs::path root = fs::temp_directory_path() / "regenreg_root";
    fs::remove_all(root);
    fs::create_directories(root / "data" / "honorifics");
    fs::create_directories(root / "data" / "pron_colloquial");
    fs::create_directories(root / "data" / "abbreviations");
    fs::create_directories(root / "store");
    write(root / "data" / "honorifics" / "honorific_register.tsv",
          "# base register\ngzigs\tlta\tperception\thonorific\n");
    write(root / "data" / "pron_colloquial" / "colloquial_pron.tsv",
          "# colloquial\twylie\tgmr_pron\tclass\n"
          "tulku\tsprul sku\ttrulku\tcommunity\n");

    allcore::ProposalStore store((root / "store").string());
    const auto honId = store.propose(
        allcore::ProposalKind::HighHonorific, "tenzin", "bzhugs",
        "ceremony", "sdod", "seen in prayers", "2026-08-14");
    const auto abbId = store.propose(
        allcore::ProposalKind::Abbreviation, "tenzin", "thams+d",
        "thams cad", "", "manuscript colophon", "2026-08-14");
    const auto prnId = store.propose(
        allcore::ProposalKind::Pronunciation, "tenzin", "dgon pa",
        "gompa", "", "heard in Mundgod", "2026-08-14");
    store.rule(honId, allcore::ProposalStatus::Approved, "adam", "",
               "2026-08-14");
    store.rule(abbId, allcore::ProposalStatus::Approved, "adam", "",
               "2026-08-14");
    store.rule(prnId, allcore::ProposalStatus::Approved, "adam", "",
               "2026-08-14");
    store.save();

    auto st = allcore::regenerateApprovedRegisters(store, root.string());
    CHECK(st.honorific == 1 && st.pron == 1 && st.abbrev == 1,
          "one approved row folded per register");
    const auto honP = root / "data" / "honorifics" /
                      "honorific_register.tsv";
    const auto abbP = root / "data" / "abbreviations" /
                      "approved_abbreviations.tsv";
    const std::string hon1 = slurp(honP);
    CHECK(hon1.find("gzigs\tlta") != std::string::npos,
          "base honorific row untouched");
    CHECK(hon1.find("bzhugs\tsdod\tceremony\thigh\t# approved by adam "
                    "2026-08-14") != std::string::npos,
          "approved honorific folded with tier and provenance");
    const std::string prn1 =
        slurp(root / "data" / "pron_colloquial" / "colloquial_pron.tsv");
    CHECK(prn1.find("gompa\tdgon pa\t\tapproved\t# approved by") !=
              std::string::npos &&
          prn1.find("tulku\tsprul sku") != std::string::npos,
          "novel pronunciation folded; community row untouched");

    // idempotent: a second run is byte-identical
    const std::string abb1 = slurp(abbP);
    allcore::regenerateApprovedRegisters(store, root.string());
    CHECK(slurp(honP) == hon1 && slurp(abbP) == abb1,
          "second run changes nothing");

    // the abbreviation layer round-trips through the display table
    allcore::AbbrTable tbl;
    CHECK(tbl.load(abbP.string()), "approved abbreviations load");
    auto hits = tbl.byWylie("thams+d");
    CHECK(hits.size() == 1 && hits[0]->expWylie == "thams cad",
          "approved abbreviation resolves to its expansion");
    CHECK(!hits[0]->abbrUnicode.empty(),
          "unicode rendering generated by the proven converter");

    // a reversal falls out on the next regeneration
    store.rule(honId, allcore::ProposalStatus::Declined, "adam",
               "not attested", "2026-08-14");
    store.save();
    auto st2 = allcore::regenerateApprovedRegisters(store, root.string());
    const std::string hon2 = slurp(honP);
    CHECK(st2.honorific == 0 &&
          hon2.find("bzhugs") == std::string::npos &&
          hon2.find("gzigs\tlta") != std::string::npos,
          "declined proposal falls out; base register intact");

    fs::remove_all(root);
    std::printf("%s (%d failures)\n",
                failures ? "REGENREG SMOKE FAILED" : "REGENREG SMOKE OK",
                failures);
    return failures ? 1 : 0;
}
