#!/usr/bin/env python3
"""build_main_apparatus.py — generate the official MAIN apparatus documents.

Adam's ruling (2026-08-06), refining GMR's reuse directive (STD-008):
footnotes and bibliography entries enter the OFFICIAL apparatus only once
they are PUBLISHED by the publisher and 100% approved by Geshe Michael.
Translator-created candidates live in a separate pending queue (the app's
candidate bank) and never touch these documents.

Therefore this script compiles the MAIN documents exclusively from the
extracted banks of RELEASED volumes:
  data/extracted/mixed_nuts_notes.json         (extract_mixed_nuts_notes.py)
  data/extracted/mixed_nuts_bibliography.json  (extract_mixed_nuts_bibliography.py)

Outputs (committed, versioned — the centralized documents):
  docs/apparatus/MAIN_FOOTNOTES.md
  docs/apparatus/MAIN_BIBLIOGRAPHY.md

Rerun all three tools whenever a new volume is released.
"""
import json
import os
from collections import OrderedDict

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXTRACTED = os.path.join(HERE, "data", "extracted")
OUTDIR = os.path.join(HERE, "docs", "apparatus")

POLICY = (
    "> **Official tier.** This document is compiled ONLY from Mixed Nuts\n"
    "> translations that have been published and 100% approved by Geshe\n"
    "> Michael Roach (Adam's ruling, 2026-08-06, refining STD-008). It is\n"
    "> regenerated by `tools/build_main_apparatus.py` when a new volume is\n"
    "> released — never edited by hand, and never fed from working drafts.\n"
    "> Translator-created candidates await publication in the app's\n"
    "> pending queue and are not part of this document.\n")


def main():
    notes = json.load(open(os.path.join(EXTRACTED, "mixed_nuts_notes.json")))
    bib = json.load(
        open(os.path.join(EXTRACTED, "mixed_nuts_bibliography.json")))
    os.makedirs(OUTDIR, exist_ok=True)

    # ---- MAIN_FOOTNOTES.md — grouped by lemma, then by volume ----
    by_src = OrderedDict()
    for n in notes:
        by_src.setdefault(n["source"], []).append(n)
    with open(os.path.join(OUTDIR, "MAIN_FOOTNOTES.md"), "w") as f:
        f.write("# MAIN Footnotes — the official shared notes bank\n\n")
        f.write(POLICY + "\n")
        f.write(f"**{len(notes)} notes** from {len(by_src)} released "
                "volumes. Reuse per GMR's directive: any of these can and "
                "should be reused as their topics come up — always with "
                "the citation given here.\n\n")
        for src, ns in by_src.items():
            f.write(f"## {src} ({len(ns)} notes)\n\n")
            for n in sorted(ns, key=lambda x: x["note"]):
                f.write(f"**n.{n['note']} — {n['lemma']}**  \n"
                        f"{n['text']}\n\n")

    # ---- MAIN_BIBLIOGRAPHY.md — grouped by section, deduped on ACIP ----
    with open(os.path.join(OUTDIR, "MAIN_BIBLIOGRAPHY.md"), "w") as f:
        f.write("# MAIN Bibliography — the official shared entry bank\n\n")
        f.write(POLICY + "\n")
        secs = OrderedDict()
        for e in bib:
            key = e["section"]
            secs.setdefault(key, []).append(e)
        n_acip = sum(1 for e in bib if e["acip_refs"])
        f.write(f"**{len(bib)} entries** from the released volumes; "
                f"{n_acip} carry ACIP catalog numbers (these key the "
                "entries to input files and BDRC scans). Entries appear "
                "verbatim as published; the same work cited in two "
                "volumes appears under each (per-volume numbering is part "
                "of the published citation).\n\n")
        for sec, es in secs.items():
            f.write(f"## {sec} ({len(es)} entries)\n\n")
            for e in es:
                refs = (" · ACIP: " + ", ".join(e["acip_refs"])
                        if e["acip_refs"] else "")
                f.write(f"**{e['id']}** *({e['source']})*{refs}  \n"
                        f"{e['text']}\n\n")
    print("wrote", os.path.join(OUTDIR, "MAIN_FOOTNOTES.md"),
          "and MAIN_BIBLIOGRAPHY.md",
          f"({len(notes)} notes, {len(bib)} bibliography entries)")


if __name__ == "__main__":
    main()
