#!/usr/bin/env python3
"""build_master_rebuild_order.py — what a data-project rebuild should and
should NOT touch, re-derived from the master and the corrected engines.

WHY IT IS A SCRIPT. Three engine defects were fixed here on 2026-09-16 and the
master was built with the broken versions, so some of its stored Tibetan is
wrong. Saying which, in prose, produces a number nobody can re-derive — the
failure this project keeps meeting. This regenerates the work order from the
master that is actually present, so the data project can run it themselves and
get the same answer, or a different one if the master has moved.

THIS REPO DOES NOT FIX THE DATA. CLAUDE.md: the app imports a release and never
owns it; do not fork it. Nothing here writes to data/.

THE WARNING THAT MATTERS MOST. A blanket "rebuild the tibetan field with the
fixed engine" would DESTROY information. Hundreds of entries deliberately store
more than the engine emits — a headword followed by its variants, separated by
a shad — and hundreds more store a Tibetanized Sanskrit stack where the
engine's syllable-by-syllable reading is simply wrong (ga nya dzi ra is
གཉྫི་ར, not ག་ཉ་ཛི་ར). Only class A below is safe to rewrite mechanically.

Usage:  python3 tools/build_master_rebuild_order.py [--master PATH] [--out PATH]
"""
import collections
import gzip
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "engines"))
from ewts_unicode import wylie_to_unicode  # noqa: E402

MASTER = os.path.join(ROOT, "data", "hgm_dictionary_v27_2.json.gz")
OUT = os.path.join(ROOT, "docs", "MASTER_REBUILD_ORDER.md")
SUBV = re.compile(r"(?<=[a-z])v")
DOUBLE_VOWEL = re.compile(r"[ིེོུ]{2,}")


def classify(wylie, tibetan, engine):
    """A is mechanical. Everything else is a reading, and says so."""
    if "-" in tibetan:
        return "A"
    if tibetan.startswith(engine) or engine in tibetan:
        return "B"
    if DOUBLE_VOWEL.search(tibetan):
        return "E-vowel"
    if len(tibetan) < len(engine) * 0.6:
        return "E-truncated"
    if "༹" in tibetan:
        return "E-wazur"
    return "E-other"


def main():
    master = MASTER
    out = OUT
    if "--master" in sys.argv:
        master = sys.argv[sys.argv.index("--master") + 1]
    if "--out" in sys.argv:
        out = sys.argv[sys.argv.index("--out") + 1]

    d = json.load(gzip.open(master, "rt", encoding="utf-8"))
    ents = d["unified_entries"]
    cnt = collections.Counter()
    binding = collections.Counter()
    samples = collections.defaultdict(list)

    for e in ents:
        w, t = e.get("wylie"), e.get("tibetan")
        if not w or not t:
            cnt["skipped: no wylie or no tibetan"] += 1
            continue
        try:
            u, ok = wylie_to_unicode(w)
        except Exception as ex:                       # the oracle raises; see TODO
            cnt["engine RAISES on this wylie"] += 1
            continue
        if not ok:
            cnt["engine refuses, flagged rather than guessed"] += 1
            if SUBV.search(w):
                cnt["  ..of which the WYLIE holds an invalid v"] += 1
            continue
        if u == t:
            cnt["already matches the corrected engine"] += 1
            continue
        k = classify(w, t, u)
        cnt[k] += 1
        if e.get("hgm_gloss"):
            binding[k] += 1
        if len(samples[k]) < 4:
            samples[k].append((w, t, u, bool(e.get("hgm_gloss"))))

    total_diff = sum(v for k, v in cnt.items() if k in
                     ("A", "B", "E-vowel", "E-truncated", "E-wazur", "E-other"))
    E = sum(v for k, v in cnt.items() if k.startswith("E"))
    Eb = sum(v for k, v in binding.items() if k.startswith("E"))

    b = []
    b.append("# Master rebuild work order\n")
    b.append("*Generated by `python3 tools/build_master_rebuild_order.py`. "
             "Re-run it against any master to get its own answer — no figure "
             "here is transcribed.*\n")
    b.append("**This repo has not modified any data.** CLAUDE.md: the app "
             "imports a release and never owns it. This is a handoff.\n")
    b.append("Master read: `%s`, **%d unified entries**.\n"
             % (os.path.relpath(master, ROOT), len(ents)))
    b.append("## Where the master stands against the corrected engine\n")
    b.append("| | entries |")
    b.append("|---|---|")
    for k, v in cnt.most_common():
        if k in ("A", "B") or k.startswith("E"):
            continue
        b.append("| %s | %d |" % (k, v))
    b.append("| **differs from the corrected engine** | **%d** |" % total_diff)
    b.append("""
## What to rebuild, and what to leave alone

### A — rebuild. %d entries, %d of them binding.

The stored Tibetan holds a literal ASCII HYPHEN-MINUS (U+002D), which is not a
Tibetan character. These are the `g-y` entries: the engine used to refuse the
wylie outright, so whatever built the field fell back to passing the wylie
through verbatim. The corrected engine reads them, and its output is the
correct Tibetan. **Safe to write mechanically.**
""" % (cnt["A"], binding["A"]))
    for w, t, u, bd in samples["A"]:
        b.append("- `%s` — stored %s → **%s**%s" %
                 (w, t, u, "  ← BINDING" if bd else ""))
    b.append("""
### B — leave alone. %d entries.

The stored value CONTAINS the engine's output and then says more: a headword
followed by its variants, separated by a shad. A blanket rebuild would delete
the variants. These are not defects.
""" % cnt["B"])
    for w, t, u, bd in samples["B"][:3]:
        b.append("- `%s` — stored %s, engine emits only %s" % (w, t, u))
    b.append("""
### E — needs a reader. %d entries, %d of them binding.

Neither side can be trusted blind here, and that is the finding. Some are real
corruption; in others the STORED value is right and the engine's naive reading
is wrong.
""" % (E, Eb))
    for k, title in (("E-other", "stored begins differently, or punctuation differs"),
                     ("E-truncated", "stored is a fragment of the headword"),
                     ("E-vowel", "doubled vowel sign in the stored value"),
                     ("E-wazur", "wa-zur stored as BA + TSA-PHRU")):
        if not cnt[k]:
            continue
        b.append("\n**%s** — %d (%d binding)\n" % (title, cnt[k], binding[k]))
        for w, t, u, bd in samples[k]:
            b.append("- `%s` — stored %s / engine %s%s" %
                     (w, t, u, "  ← BINDING" if bd else ""))
    b.append("""
## The engine commits a rebuild must be run with

- `5c3d77f8` — `-` accepted as the prefix disambiguator EWTS writes `.`
- `e2f341b1` — wa-zur on an already-formed stack (`grwa` → གྲྭ)
- `d07b363e` — ACIP `V` read as wa-zur in `acip_to_ewts`

A rebuild run with anything earlier writes a different wrong answer.

## After the release lands

Rebuild the spine, rebuild the iOS drill pack, re-press. The phone keeps the
old values until the pack is rebuilt.
""")
    io.open(out, "w", encoding="utf-8").write("\n".join(b) + "\n")
    print("  wrote %s" % os.path.relpath(out, ROOT))
    print("  A rebuild=%d (binding %d)   B leave=%d   E reader=%d (binding %d)"
          % (cnt["A"], binding["A"], cnt["B"], E, Eb))
    return 0


if __name__ == "__main__":
    sys.exit(main())
