#!/usr/bin/env python3
"""The published dictionary may only SHOW what the layer BANKED.

docs/michael_dictionary.html is the artifact Adam actually looks at, and it
is generated by a second code path (build_dictionary_view.py) that reads the
layer and reshapes it. Every gate before this one stopped at the layer. That
left a hole big enough to drive a falsehood through: the layer could be
provably verbatim and the page in front of the reader could still say
something else, because nothing compared the two.

The invariant is deliberately narrow, because a loose one would be worthless:

    every published (headword, English) pair is EITHER exactly a banked pair,
    OR a prefix of one produced by trim_glued() — and nothing else, ever.

trim_glued cuts a following section's heading back off the English (a
registered digitisation artefact, E-037/E-038 class). Truncation can only ever
remove text, so a prefix cannot introduce a claim the layer did not make.
Anything that is neither exact nor a prefix is the display layer inventing,
and that is a hard zero.

The phonetics band is checked too, and separately: it must stay disjoint from
depth 5 PAIRWISE. The same Tibetan word legitimately has a transcription in
one band and a translation in the other — 116 headwords do — so a headword
test would be a false alarm. An identical (headword, English) pair in both is
the real failure, and there are none.
"""
import io, json, os, sys
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VIEW = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    ROOT, 'docs/michael_dictionary.html')
FULL = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    ROOT, 'data/alignment/alignment_full_v1.json')
EVID = sys.argv[3] if len(sys.argv) > 3 else os.path.join(
    ROOT, 'data/alignment/alignment_evidence_v1.json')

CEILING = {
    'INVENTED-BY-THE-VIEW': 0,        # neither banked nor a trim of a banked
    'phonetics-leaked-into-depth-5': 0,
    'trimmed (trim_glued)': 40,       # 27 measured 2026-08-28
}

def payload(html):
    key = 'const PAYLOAD = '
    i = html.index(key) + len(key)
    # raw_decode, not brace counting - the JSON is full of braces inside strings
    return json.JSONDecoder().raw_decode(html, i)[0]

def rows(band):
    for hw, _x, senses in band:
        for eng, refs in senses:
            yield hw, eng, refs

def classify(P, full, ev):
    byTib = {}
    for l in full['links']:
        if l.get('tib') and l.get('eng'):
            byTib.setdefault(l['tib'], set()).add(l['eng'])
    for hw, senses in ev['pairs'].items():
        for s in senses:
            if s.get('eng'):
                byTib.setdefault(hw, set()).add(s['eng'])

    t, bad = Counter(), []
    bands = list(P['depths'].items()) + [('phon', P['phonetics'])]
    for d, band in bands:
        for hw, eng, refs in rows(band):
            banked = byTib.get(hw, ())
            if eng in banked:
                t['exact'] += 1
            elif any(b.startswith(eng) for b in banked):
                t['trimmed (trim_glued)'] += 1
            else:
                t['INVENTED-BY-THE-VIEW'] += 1
                bad.append((d, hw[:60], eng[:90]))

    php = {(hw, e) for hw, e, _ in rows(P['phonetics'])}
    d5p = {(hw, e) for hw, e, _ in rows(P['depths'].get('5', []))}
    both = php & d5p
    t['phonetics-leaked-into-depth-5'] = len(both)
    return t, bad, sorted(both)[:6]

def main():
    P = payload(io.open(VIEW, encoding='utf-8').read())
    full = json.load(io.open(FULL, encoding='utf-8'))
    ev = json.load(io.open(EVID, encoding='utf-8'))
    t, bad, both = classify(P, full, ev)
    fail = False
    for cls, cap in CEILING.items():
        n = t.get(cls, 0)
        if n > cap:
            fail = True
            print('FAIL %s: %d > ceiling %d' % (cls, n, cap))
            for r in (bad if cls == 'INVENTED-BY-THE-VIEW' else both)[:10]:
                print('     ', r)
    if fail:
        return 1
    total = t['exact'] + t['trimmed (trim_glued)']
    print('view matches layer: %d published rows, %d exactly as banked, '
          '%d trimmed of a glued heading, 0 invented; phonetics band and '
          'depth 5 share no pair' % (total, t['exact'], t['trimmed (trim_glued)']))
    return 0

if __name__ == '__main__':
    sys.exit(main())
